version: '3.6'
services:
  db:
    image: 'mysql:8.0'
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rezijiser
    volumes:
      - ./mysql:/var/lib/mysql:rw
    ports:
      - 3306:3306