SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE test(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` varchar(64) CHARACTER SET utf16 COLLATE utf16_bin NOT NULL,
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY('id')
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_bin;