SET NAMES utf8;
SET time_zone = `+00:00`;
SET foreign_key_checks = 0;
SET sql_mode = `NO_AUTO_VALUE_ON_ZERO`;

DROP TABLE test;

CREATE TABLE user(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` varchar(20) CHARACTER SET utf16 COLLATE utf16_bin NOT NULL,
    `surname` varchar(32) CHARACTER SET utf16 COLLATE utf16_bin NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `email` varchar(64) CHARACTER SET utf16 NOT NULL,
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_bin;

CREATE TABLE power(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `counter` DECIMAL(6,4) NOT NULL, -- kWh
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `power_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE water(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `counter` DECIMAL(6,4) NOT NULL, -- m^3
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `water_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE gas(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `counter` DECIMAL(6,4) NOT NULL, -- ???
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `gas_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE reservation(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `reservation_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE communal(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `communal_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE hrt(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `hrt_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE telecommunications(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_user` INT NOT NULL,
    `cost` DECIMAL(6,2) NOT NULL,
    `payday` DATE NOT NULL,
    `date_paid` DATE NOT NULL,
    `time_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(id),
    CONSTRAINT `telecommunications_user_fk1` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);